"use client"
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "../../components/Layout/Header";
import Footer from "../../components/Layout/Footer";
import { TitleProvider } from "../../context/TitleContext";
import { AuthProvider } from "../../context/authContext";
import { Provider } from "react-redux";
import { store, persistor } from "../../store";
import { PersistGate } from "redux-persist/integration/react";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
/*
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};*/

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >

  <Provider store={store}>
          <PersistGate loading={null} persistor={persistor}>
            <TitleProvider> 
            <AuthProvider>
              <Header />
              {children}
              <Footer />

            </AuthProvider>
         
            </TitleProvider>  

         </PersistGate>
        </Provider>
        
     
      </body>
    </html>
  );
}


/*
  <Provider store={store}>
  <Header />
  {children}
  <Footer />
</Provider>
*/